name: Test_on_develop

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  run-unitTest:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Mise & Set PATH
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Trust mise config
        run: mise trust

      - name: Install Tuist via mise
        run: mise install tuist

      - name: Resolve dependencies
        run: mise x -- tuist install

      - name: Generate Xcode project
        run: mise x -- tuist generate

      - name: Run Unit Tests
        run: mise x -- tuist test HotSpotTests
